"""location-aware pricing, user foundation, search indexing

Revision ID: cf367f1b212d
Revises: 
Create Date: 2026-06-22 08:52:33.038514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf367f1b212d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bill_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bill_uploads_job_id', 'bill_uploads', ['job_id'], unique=False)
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bill_upload_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_upload_id'], ['bill_uploads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_item_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['basket_item_id'], ['basket_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_item_id')
    )
    op.add_column('product_listings', sa.Column('location_key', sa.String(length=64), nullable=True))
    op.create_index('ix_product_listings_product_location', 'product_listings', ['product_id', 'location_key'], unique=False)
    op.create_index('ix_products_brand_trgm', 'products', ['brand'], unique=False, postgresql_using='gin', postgresql_ops={'brand': 'gin_trgm_ops'})
    op.create_index('ix_products_name_trgm', 'products', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_name_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index('ix_products_brand_trgm', table_name='products', postgresql_using='gin', postgresql_ops={'brand': 'gin_trgm_ops'})
    op.drop_index('ix_product_listings_product_location', table_name='product_listings')
    op.drop_column('product_listings', 'location_key')
    op.drop_table('basket_recommendations')
    op.drop_table('basket_items')
    op.drop_table('baskets')
    op.drop_index('ix_bill_uploads_job_id', table_name='bill_uploads')
    op.drop_table('bill_uploads')
    op.drop_table('users')
    # ### end Alembic commands ###
