/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as UnlocksRouteImport } from './routes/unlocks'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ThisWeekRouteImport } from './routes/this-week'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as BetaRouteImport } from './routes/beta'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlocksRoute = UnlocksRouteImport.update({
  id: '/unlocks',
  path: '/unlocks',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisWeekRoute = ThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const BetaRoute = BetaRouteImport.update({
  id: '/beta',
  path: '/beta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/teach': typeof TeachRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/unlocks': typeof UnlocksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/teach': typeof TeachRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/unlocks': typeof UnlocksRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beta': typeof BetaRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/knowledge': typeof KnowledgeRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/teach': typeof TeachRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/unlocks': typeof UnlocksRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beta'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/knowledge'
    | '/pricing'
    | '/products'
    | '/teach'
    | '/this-week'
    | '/today'
    | '/unlocks'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beta'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/knowledge'
    | '/pricing'
    | '/products'
    | '/teach'
    | '/this-week'
    | '/today'
    | '/unlocks'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/beta'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/knowledge'
    | '/pricing'
    | '/products'
    | '/teach'
    | '/this-week'
    | '/today'
    | '/unlocks'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BetaRoute: typeof BetaRoute
  FeedbackRoute: typeof FeedbackRoute
  HabitsRoute: typeof HabitsRoute
  HouseholdRoute: typeof HouseholdRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  TeachRoute: typeof TeachRoute
  ThisWeekRoute: typeof ThisWeekRoute
  TodayRoute: typeof TodayRoute
  UnlocksRoute: typeof UnlocksRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlocks': {
      id: '/unlocks'
      path: '/unlocks'
      fullPath: '/unlocks'
      preLoaderRoute: typeof UnlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-week': {
      id: '/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof ThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beta': {
      id: '/beta'
      path: '/beta'
      fullPath: '/beta'
      preLoaderRoute: typeof BetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BetaRoute: BetaRoute,
  FeedbackRoute: FeedbackRoute,
  HabitsRoute: HabitsRoute,
  HouseholdRoute: HouseholdRoute,
  KnowledgeRoute: KnowledgeRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  TeachRoute: TeachRoute,
  ThisWeekRoute: ThisWeekRoute,
  TodayRoute: TodayRoute,
  UnlocksRoute: UnlocksRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
