/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ThisWeekRouteImport } from './routes/this-week'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as BillCheckRouteImport } from './routes/bill-check'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisWeekRoute = ThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const BillCheckRoute = BillCheckRouteImport.update({
  id: '/bill-check',
  path: '/bill-check',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bill-check': typeof BillCheckRoute
  '/discovery': typeof DiscoveryRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/memory': typeof MemoryRoute
  '/pricing': typeof PricingRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bill-check': typeof BillCheckRoute
  '/discovery': typeof DiscoveryRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/memory': typeof MemoryRoute
  '/pricing': typeof PricingRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bill-check': typeof BillCheckRoute
  '/discovery': typeof DiscoveryRoute
  '/feedback': typeof FeedbackRoute
  '/habits': typeof HabitsRoute
  '/household': typeof HouseholdRoute
  '/memory': typeof MemoryRoute
  '/pricing': typeof PricingRoute
  '/this-week': typeof ThisWeekRoute
  '/today': typeof TodayRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bill-check'
    | '/discovery'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/memory'
    | '/pricing'
    | '/this-week'
    | '/today'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bill-check'
    | '/discovery'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/memory'
    | '/pricing'
    | '/this-week'
    | '/today'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/bill-check'
    | '/discovery'
    | '/feedback'
    | '/habits'
    | '/household'
    | '/memory'
    | '/pricing'
    | '/this-week'
    | '/today'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillCheckRoute: typeof BillCheckRoute
  DiscoveryRoute: typeof DiscoveryRoute
  FeedbackRoute: typeof FeedbackRoute
  HabitsRoute: typeof HabitsRoute
  HouseholdRoute: typeof HouseholdRoute
  MemoryRoute: typeof MemoryRoute
  PricingRoute: typeof PricingRoute
  ThisWeekRoute: typeof ThisWeekRoute
  TodayRoute: typeof TodayRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-week': {
      id: '/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof ThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-check': {
      id: '/bill-check'
      path: '/bill-check'
      fullPath: '/bill-check'
      preLoaderRoute: typeof BillCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillCheckRoute: BillCheckRoute,
  DiscoveryRoute: DiscoveryRoute,
  FeedbackRoute: FeedbackRoute,
  HabitsRoute: HabitsRoute,
  HouseholdRoute: HouseholdRoute,
  MemoryRoute: MemoryRoute,
  PricingRoute: PricingRoute,
  ThisWeekRoute: ThisWeekRoute,
  TodayRoute: TodayRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
